cargo-features = ["edition2024"]

[package]
name = "hello_world"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-program = "2.2.0"

[features]
no-entrypoint = []

[lib]
name = "hello_world"
crate-type = ["cdylib", "lib"]
